version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  grana-flow:
    build:
      context: .  # Caminho relativo do diretório atual, onde está o Dockerfile
    environment:
      APP_NAME: grana-flow
      CONTEXT_PATH: /grana-flow/api
      DS_DRIVER: oracle.jdbc.OracleDriver
      DS_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1  # Referência ao serviço oracle-db
      DS_USERNAME: SYSTEM  # Username do Oracle
      DS_PASSWORD: gr4n4fl0w#  # Senha do Oracle
      DS_SCHEMA: SYSTEM  # Schema do Oracle
      DS_DIALECT: org.hibernate.dialect.OracleDialect  # Dialeto adequado para o Oracle 12c
      PROFILES_ACTIVE: dev  # Ambiente ativo (dev, prod, etc.)
      SECRET_KEY: hc08sjjSnsqVYmtp/gfuQRMeQNXDRo6gkLWT50p8rbQ=  # Chave secreta para segurança
      TZ: America/Fortaleza  # Fuso horário
    networks:
      - app-network
    ports:
      - "8080:8080"  # Porta exposta do container para o host
    depends_on:
      oracle-db:
        condition: service_healthy  # Aguarda o banco estar pronto antes de iniciar
    volumes:
      - grana-flow-data:/app/data  # Volume para persistir dados da aplicação

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe  # Imagem do banco de dados Oracle
    environment:
      ORACLE_PASSWORD: gr4n4fl0w#  # Senha do usuário SYS e SYSTEM
      ORACLE_SID: xe  # SID do Oracle
    networks:
      - app-network
    ports:
      - "1521:1521"  # Porta do banco de dados
    volumes:
      - oracle-data:/opt/oracle/oradata  # Volume para persistir dados do Oracle
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S SYSTEM/gr4n4fl0w#@XEPDB1"]
      interval: 10s  # Intervalo entre as verificações
      timeout: 5s  # Timeout para a verificação
      retries: 10  # Número de tentativas antes de marcar como "não saudável"

# Volumes para persistência de dados
volumes:
  grana-flow-data:
  oracle-data:
