version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  grana-flow:
    build:
      context: .
    environment:
      APP_NAME: ${APP_NAME}
      CONTEXT_PATH: ${CONTEXT_PATH}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DS_DRIVER_CLASS_NAME: ${DS_DRIVER_CLASS_NAME}
      DS_URL: ${DS_URL}
      DS_USERNAME: ${DS_USERNAME}
      DS_PASSWORD: ${DS_PASSWORD}
      DS_SCHEMA: ${DS_SCHEMA}
      DS_DIALECT: ${DS_DIALECT}
      PROFILES_ACTIVE: ${PROFILES_ACTIVE}
      SECRET_KEY: ${SECRET_KEY}
      TZ: ${TZ}
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    volumes:
      - grana-flow-data:/app/data

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_SID: ${ORACLE_SID}
    networks:
      - app-network
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S SYSTEM/gr4n4fl0w#@XEPDB1"]
      interval: 10s
      timeout: 5s
      retries: 10  # Número de tentativas antes de marcar como "não saudável"

volumes:
  grana-flow-data:
  oracle-data:
