package com.granaflow.lancamento;

public enum EnumTipoCusto {

	VESTUARIO, ALIMENTACAO, COLEGIO, MOVEL, TECNOLOGIA, ENERGIA, AGUA, ALUGUEL, INTERNET, ACADEMIA, MOTORISTA_APP,
	FARMACIA, DENTISTA, OFTALMOLOGISTA, BRINQUEDO, OUTRO, LIVRO;
}
